### ISSUE TITLE
Initial format

### ISSUE THREAD

**Issue by spohess** [pjdietz/sublime-date-formatter#1]
Hi, I try to use your plugin, but I'm from brazil and my date format is d/m/Y and the Date Formatter expects m/d/Y, right? I try change this, but I did not succeed. Have somehow?

Congratulations for plugin, is really good!

Thanks a lot!

**Comment by pjdietz** [comment]
The plugin runs all the date formatting in PHP CLI, so you should be able to get this to work by configuring the php.ini file on your system for your locale.

**Comment by spohess** [comment]
Thanks @pjdietz
